server:
    port: 9000

spring:
  jpa:
    generate-ddl: false
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost/classicmodels
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver